# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/minimal-mistakes@4.20.2
minimal_mistakes_skin: default

# Site settings
locale: "en-US"
title: Paulo Sampaio
title_separator: "-"
subtitle: Projects, ideas and a little about me
description: Paulo Sampaio's online porfolio. Data science, machine learning, computer vision and whatever else is on my mind!
baseurl: "/"
comments:
  provider: "custom"
search: true
github_user: pauloesampaio
repository: "pauloesampaio/pauloesampaio.github.io"

# SEO Related
google_site_verification: "XEDt9F4XMhWbVsaFSHIsFpdoy1FC1PwIPHQ9ZPkbyq4"

# Social sharing
twitter:
  username: "sampaio_paulo"
og_image: "assets/images/bio-photo.png"
social:
  type: Person
  name: Paulo Sampaio
  links:
    - "https://www.linkedin.com/in/paulosampaio"
    - "https://github.com/pauloesampaio"
    - "https://instagram.com/paulo_sampaio"
    - "https://twitter.com/sampaio_paulo"
    - "https://www.facebook.com/paulo.ed"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-178010206-1"
    anonymize_ip: false # default

# Site author
author:
  name: "Paulo Sampaio"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Data science and advanced analytics specialist, consultant and instructor"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/paulosampaio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pauloesampaio"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paulo_sampaio"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sampaio_paulo"

# Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/paulosampaio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pauloesampaio"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paulo_sampaio"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sampaio_paulo"

# Reading files
include:
  - _pages
  - _posts
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /_posts/page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata
